[project]
name = "lantime-prometheus-exporter"
version = "0.1.0"
description = ""
readme = "README.md"
dependencies = [
    "loguru>=0.7.3",
    "prometheus-client>=0.23.1",
]
requires-python = ">=3.13"
